[package]
name = "lingo_morph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
_log = { package = "log", version = "0.4", optional = true }

[features]
default = ["logging"]
logging = ["dep:_log"]
